### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by radionerd** [Jikstra/serial2midi#1]
sudo apt-get install libasound2-dev

Thanks for sharing such a brilliant and simple idea that everyone else missed.

**Comment by Jikstra** [comment]
Happy that it helps you :) Probably that lib is needed for the AUR package too. If you want to add a Debian/Ubuntu section to the README, i would appreciate a PR.

**Comment by radionerd** [comment]
Hi Jikstra,

I'll figure out how to do a PR and make it so once I have your code up and
running.

I have a Yamaha PSR-520 keyboard that I'm hoping to connect with a laptop
running Ubuntu 21.04 via a USB serial dongle+interface and your serial2midi
driver.
The AliExpress midi lead I bought only functions sometimes from the
keyboard to the PC, I suspect due to the baud rate being slightly off as
there is no visible crystal on the PCB.
So, I would like to try your approach while I wait for a Roland UM-One midi
lead to arrive. We're in Covid lockdown in New Zealand at the moment, it
could be a while coming.

I've hit a bit of a road block running your code going the route: git clone
https://github.com/jikstra/serial2midi.git
 ; pip install -r dependencies.txt
I get a runtime error as follows:
***@***.***:~/Projects/serial2midi$ python3 main.py /dev/ttyUSB0
Traceback (most recent call last):
  File "/home/richard/Projects/serial2midi/main.py", line 175, in <module>
    main()
  File "/home/richard/Projects/serial2midi/main.py", line 172, in main
    serial_to_midi.run()
  File "/home/richard/Projects/serial2midi/main.py", line 70, in run
    virtualMidiInput = rtmidi.MidiIn()
AttributeError: module 'rtmidi' has no attribute 'MidiIn'

I get the same error whether running Ubuntu 21.04 on RaspberryPi4 or my
Intel laptop.
There seem to be at least three rtmidi libraries for python. I thought I
would check with you before diving in too deep.
Thanks in advance for any suggestions that you may have regarding where to
look to solve the problem.

Regards

Richard Jones

**Comment by Jikstra** [comment]
@radionerd oh yes, it was old/wrong dependencies. Somehow the python ecosystem is quite confusing, a lot of very similiar named libraries, that even have the same name when imported, but have different apis. It's annoying. I updated dependencies.txt, have a look if that works for you now.
Maybe first run `pip uninstall serial && pip uninstall rtmidi` and then after a pull, again the `pip install -r dependencies.txt`. The correct names of the needed modules is `pyserial` and `python-rtmidi`.
